sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'root#top'

  post 'posts' => 'posts#create' #../postsのurlにpostでリクしたときにpostsコントローラーのcreateアクションが呼び出される


  get 'posts' => 'posts#index'

  #投稿１件ごとの詳細を表示
  get 'posts/:id' => 'posts#show', as: 'post'#as: '名前' はURLを簡潔に
  		#.../posts/1 や .../posts/3 に該当する

  #どの投稿を編集するかを識別する(詳細画面の表示と同じように)
  get 'posts/:id/edit' => 'posts#edit', as: 'edit_post'
  #posts/〜〜/edit というURL全て該当↑↑
  patch 'posts/:id' => 'posts#update', as: 'update_post'#新規はpost,更新はpatch
  #destroyアクションにつながるようにルーティング追加
  delete 'posts/:id' => 'posts#destroy', as: 'destroy_post'
end

sample_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample_app/app/models/post.rb
class Post < ApplicationRecord
#refileを使う時はモデル(postモデルにattachmentメソッドを
	attachment :image
end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

sample_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
  	#空のモデルをビューへ渡す
    	@post = Post.new #空モデル作成を左へ
    end

    #送信されたフォーム値をDBに。(postインスタンスを生成しtitle,bodyに値セット後、saveメソッド呼)
    def create #privateより上に
    	#ストロングパラメーター使用
    	post = Post.new(post_params)#ローカル変数なので@なし。アクション内のみ使用可
        	#DBへ保存
    	post.save
    	#保存後トップ画面へリダイレクト
    	redirect_to post_path(post.id)#どの投稿かを指定.id
    end#↑↑投稿後すぐ内容を観れるよう'/top'を変更(詳細画面へリダイレクト)


    def index
      @posts = Post.all
    end#全てのデータ取って@postsへ。全てなので複数

    #URL中のidをコントローラーで受け取るroutes.rbから
    def show
      @post = Post.find(params[:id])
    end#params[:id]で:idにある値を取得。URL/posts/1ならparamsには「{id: 1}」ハッシュがある

    #編集するには投稿データ必要。なので保存データ取得
    def edit
      @post = Post.find(params[:id])
    end

    def update #投稿の更新
      post = Post.find(params[:id])
      post.update(post_params)
      redirect_to post_path(post.id)
    end

  #showの削除リンク押すとそこのpostのid含めたURLが送信。それをもとにレコード探しDBから削除する
    def destroy
      post = Post.find(params[:id])#レコード(データ)を１取得
      post.destroy#レコードをDBから削除
      redirect_to posts_path#post一覧へリダイレクト
    end

    #create作成　フォームからのデータ受け取り、そのデータをモデルを介しDBに保存
    private #メソッド前に、認識されなくなる。下に

    def post_params #投稿ボタンがトリガー、postsコントのcreateアクフォームに入った値が送信される
    	params.require(:post).permit(:title, :body, :image)
    end# 			　モデル名			　カラムな     gemのImagemagick使う時追加(:image)
  end

sample_app/app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
		
	end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper
end

sample_app/app/helpers/ports_helper.rb
module PortsHelper
end

sample_app/app/helpers/root_helper.rb
module RootHelper
end

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

sample_app/app/views/posts/edit.html.erb
<!-- フォームに編集したいデータ入れるにはform_for利用。インスタ変数にあるモデル渡すだけで値を入れてくれる -->
<h1>編集画面</h1>
<%= form_for(@post) do |f| %>
	<h4>タイトル</h4>
	<% f.text_field :title %>
	<h4>本文</h4>
	<%= f.text_area :body %>
	<%= f.submit '保存' %>
<% end %>

sample_app/app/views/posts/index.html.erb
<!-- ビューファイルにPostsControllerの @postsから取得した投稿データ全てを表示する処理を-->
<h1>投稿一覧</h1>
<% @posts.each do |post| %><!--@posts.each でPostのレコード数だけループする-->
<p>タイトル</p>
<!-- リンクlink_toメソッドを。投稿一覧から詳細ページへ -->
    <span>
    	<%=link_to post.title, post_path(post.id) %>
		<!-- リンクに表示させる文　　↑リンク先URL"/posts/#{post.id}"を上に省略可 -->
    </span>
    <!-- 投稿された画像を一覧画面と詳細画面に表示させる -->
    <p>画像</p>
    <%= attachment_image_tag post, :image, :fill, 100, 100, format: 'jpeg' %>
										<!--fillで高さ幅 formatで拡張子 -->
<% end %>

sample_app/app/views/posts/new.html.erb
<h1>新規投稿</h1>
<!-- form_forの部分(htmlのformタグを作成する機能) -->
<%= form_for(@post) do |f| %>

	<h4>タイトル</h4>
	<%= f.text_field :title %>

	<h4>本文</h4>
	<%= f.text_area :body %>

	<!-- 画像gem追加後追加 -->
	<h4>画像</h4>
	<%= f.attachment_field :image %>
	<!-- ↑↑ -->

	<%= f.submit '投稿' %>

<% end %>

sample_app/app/views/posts/show.html.erb
<h2>タイトル</h2>
<p><%= @post.title %></p>
<h2>本文</h2>
<p><%= @post.body %></p>
<!-- 投稿された画像を一覧画面と詳細画面に表示させる -->
<h2>画像</h2>
<%= attachment_image_tag @post, :image, :fill, 300, 300, format: 'jpeg' %>
<!--編集結果は詳細ページで見せるためここへ  -->
<%= link_to "編集", edit_post_path(@post.id) %>
<!-- 削除ボタン、誤発防止のために確認画面も表示させる -->
<%= link_to "削除", destroy_post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

sample_app/app/views/root/top.html.erb
<h1>ここはTopページです</h1>